2025-08-15 22:19:03 - reconciliation.mellat_received_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 3964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-15 22:19:03,269 - ERROR - Error reconciling Bank Transfer 3964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 22:10:22 - reconciliation.mellat_received_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 3964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 22:10:22,692 - ERROR - Error reconciling Bank Transfer 3964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 22:23:36,009 - ERROR - هیچ تراکنش مغایرت‌گیری نشده‌ای برای این بانک وجود ندارد
2025-08-16 22:24:22 - reconciliation.mellat_received_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 4964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 22:24:22,982 - ERROR - Error reconciling Bank Transfer 4964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 22:27:12 - reconciliation.reconciliation_logic - ERROR - خطا در فرآیند مغایرت‌گیری: reconcile_mellat_pos() missing 1 required positional argument: 'on_complete'
2025-08-16 22:27:12,307 - ERROR - خطا در فرآیند مغایرت‌گیری: reconcile_mellat_pos() missing 1 required positional argument: 'on_complete'
2025-08-16 22:27:12,308 - ERROR - خطا در فرآیند مغایرت‌گیری: reconcile_mellat_pos() missing 1 required positional argument: 'on_complete'
2025-08-16 22:40:28 - reconciliation.mellat_received_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 22:40:28,823 - ERROR - Error reconciling Bank Transfer 5964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5481: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,268 - ERROR - Error reconciling Bank Transfer 5481: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5484: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,351 - ERROR - Error reconciling Bank Transfer 5484: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5498: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,403 - ERROR - Error reconciling Bank Transfer 5498: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5499: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,441 - ERROR - Error reconciling Bank Transfer 5499: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5504: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,532 - ERROR - Error reconciling Bank Transfer 5504: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5505: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,567 - ERROR - Error reconciling Bank Transfer 5505: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5506: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,615 - ERROR - Error reconciling Bank Transfer 5506: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5507: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,640 - ERROR - Error reconciling Bank Transfer 5507: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5508: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,735 - ERROR - Error reconciling Bank Transfer 5508: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5509: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,766 - ERROR - Error reconciling Bank Transfer 5509: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5510: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,795 - ERROR - Error reconciling Bank Transfer 5510: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5515: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,824 - ERROR - Error reconciling Bank Transfer 5515: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_received_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 23:20:26,825 - ERROR - Error reconciling Bank Transfer 5964: 'ReconciliationUIHandler' object has no attribute 'get_parent'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_received_transfer_reconciliation.py", line 86, in _reconcile_single_transfer
    dialog = ManualReconciliationDialog(ui_handler.get_parent(), matches)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReconciliationUIHandler' object has no attribute 'get_parent'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5516: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,851 - ERROR - Error reconciling Bank Transfer 5516: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5517: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,899 - ERROR - Error reconciling Bank Transfer 5517: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5518: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:26,936 - ERROR - Error reconciling Bank Transfer 5518: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5524: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,041 - ERROR - Error reconciling Bank Transfer 5524: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5533: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,165 - ERROR - Error reconciling Bank Transfer 5533: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5540: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,200 - ERROR - Error reconciling Bank Transfer 5540: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5541: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,241 - ERROR - Error reconciling Bank Transfer 5541: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5565: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,374 - ERROR - Error reconciling Bank Transfer 5565: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5585: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,402 - ERROR - Error reconciling Bank Transfer 5585: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5586: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,441 - ERROR - Error reconciling Bank Transfer 5586: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5588: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,492 - ERROR - Error reconciling Bank Transfer 5588: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5594: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,544 - ERROR - Error reconciling Bank Transfer 5594: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5595: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,593 - ERROR - Error reconciling Bank Transfer 5595: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5596: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,628 - ERROR - Error reconciling Bank Transfer 5596: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5597: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,689 - ERROR - Error reconciling Bank Transfer 5597: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5598: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,746 - ERROR - Error reconciling Bank Transfer 5598: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5599: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,786 - ERROR - Error reconciling Bank Transfer 5599: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5600: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,823 - ERROR - Error reconciling Bank Transfer 5600: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5601: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,853 - ERROR - Error reconciling Bank Transfer 5601: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5602: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,883 - ERROR - Error reconciling Bank Transfer 5602: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5603: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,918 - ERROR - Error reconciling Bank Transfer 5603: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5604: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:27,974 - ERROR - Error reconciling Bank Transfer 5604: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5605: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,006 - ERROR - Error reconciling Bank Transfer 5605: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5606: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,042 - ERROR - Error reconciling Bank Transfer 5606: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5607: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,107 - ERROR - Error reconciling Bank Transfer 5607: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5608: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,164 - ERROR - Error reconciling Bank Transfer 5608: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5609: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,232 - ERROR - Error reconciling Bank Transfer 5609: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5610: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,285 - ERROR - Error reconciling Bank Transfer 5610: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5611: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,314 - ERROR - Error reconciling Bank Transfer 5611: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5612: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,365 - ERROR - Error reconciling Bank Transfer 5612: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5613: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,419 - ERROR - Error reconciling Bank Transfer 5613: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5614: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,443 - ERROR - Error reconciling Bank Transfer 5614: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5615: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,471 - ERROR - Error reconciling Bank Transfer 5615: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5616: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,515 - ERROR - Error reconciling Bank Transfer 5616: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5617: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,591 - ERROR - Error reconciling Bank Transfer 5617: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5618: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,633 - ERROR - Error reconciling Bank Transfer 5618: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5619: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,673 - ERROR - Error reconciling Bank Transfer 5619: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5625: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,700 - ERROR - Error reconciling Bank Transfer 5625: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5626: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,738 - ERROR - Error reconciling Bank Transfer 5626: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5627: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,788 - ERROR - Error reconciling Bank Transfer 5627: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5628: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,825 - ERROR - Error reconciling Bank Transfer 5628: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5629: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,868 - ERROR - Error reconciling Bank Transfer 5629: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5630: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,895 - ERROR - Error reconciling Bank Transfer 5630: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5631: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,924 - ERROR - Error reconciling Bank Transfer 5631: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5632: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,951 - ERROR - Error reconciling Bank Transfer 5632: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5633: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:28,999 - ERROR - Error reconciling Bank Transfer 5633: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5634: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,025 - ERROR - Error reconciling Bank Transfer 5634: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5635: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,078 - ERROR - Error reconciling Bank Transfer 5635: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5636: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,128 - ERROR - Error reconciling Bank Transfer 5636: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5637: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,176 - ERROR - Error reconciling Bank Transfer 5637: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5638: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,216 - ERROR - Error reconciling Bank Transfer 5638: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5640: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,251 - ERROR - Error reconciling Bank Transfer 5640: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5666: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,331 - ERROR - Error reconciling Bank Transfer 5666: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5672: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,369 - ERROR - Error reconciling Bank Transfer 5672: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5673: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,412 - ERROR - Error reconciling Bank Transfer 5673: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5674: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,454 - ERROR - Error reconciling Bank Transfer 5674: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5690: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,506 - ERROR - Error reconciling Bank Transfer 5690: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5691: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,556 - ERROR - Error reconciling Bank Transfer 5691: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5692: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,606 - ERROR - Error reconciling Bank Transfer 5692: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5693: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,633 - ERROR - Error reconciling Bank Transfer 5693: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5695: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,665 - ERROR - Error reconciling Bank Transfer 5695: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5701: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,722 - ERROR - Error reconciling Bank Transfer 5701: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5710: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,763 - ERROR - Error reconciling Bank Transfer 5710: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5711: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,810 - ERROR - Error reconciling Bank Transfer 5711: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5712: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,863 - ERROR - Error reconciling Bank Transfer 5712: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5719: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,941 - ERROR - Error reconciling Bank Transfer 5719: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5720: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:29,981 - ERROR - Error reconciling Bank Transfer 5720: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5721: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,025 - ERROR - Error reconciling Bank Transfer 5721: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5722: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,066 - ERROR - Error reconciling Bank Transfer 5722: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5731: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,160 - ERROR - Error reconciling Bank Transfer 5731: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5761: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,296 - ERROR - Error reconciling Bank Transfer 5761: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5767: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,376 - ERROR - Error reconciling Bank Transfer 5767: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5771: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,424 - ERROR - Error reconciling Bank Transfer 5771: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5772: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,474 - ERROR - Error reconciling Bank Transfer 5772: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5773: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,544 - ERROR - Error reconciling Bank Transfer 5773: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5774: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,604 - ERROR - Error reconciling Bank Transfer 5774: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5775: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,665 - ERROR - Error reconciling Bank Transfer 5775: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5786: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,728 - ERROR - Error reconciling Bank Transfer 5786: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5787: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,813 - ERROR - Error reconciling Bank Transfer 5787: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5801: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,849 - ERROR - Error reconciling Bank Transfer 5801: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5802: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:30,908 - ERROR - Error reconciling Bank Transfer 5802: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5825: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,007 - ERROR - Error reconciling Bank Transfer 5825: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5843: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,066 - ERROR - Error reconciling Bank Transfer 5843: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5844: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,098 - ERROR - Error reconciling Bank Transfer 5844: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5872: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,144 - ERROR - Error reconciling Bank Transfer 5872: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5873: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,198 - ERROR - Error reconciling Bank Transfer 5873: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5901: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,476 - ERROR - Error reconciling Bank Transfer 5901: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5902: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,533 - ERROR - Error reconciling Bank Transfer 5902: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5904: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,558 - ERROR - Error reconciling Bank Transfer 5904: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5905: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,606 - ERROR - Error reconciling Bank Transfer 5905: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5906: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,657 - ERROR - Error reconciling Bank Transfer 5906: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5907: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,704 - ERROR - Error reconciling Bank Transfer 5907: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5908: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,761 - ERROR - Error reconciling Bank Transfer 5908: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5909: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,813 - ERROR - Error reconciling Bank Transfer 5909: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5910: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,868 - ERROR - Error reconciling Bank Transfer 5910: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5911: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:31,949 - ERROR - Error reconciling Bank Transfer 5911: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5913: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,020 - ERROR - Error reconciling Bank Transfer 5913: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5914: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,084 - ERROR - Error reconciling Bank Transfer 5914: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5915: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,115 - ERROR - Error reconciling Bank Transfer 5915: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5916: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,165 - ERROR - Error reconciling Bank Transfer 5916: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5917: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,239 - ERROR - Error reconciling Bank Transfer 5917: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5918: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,308 - ERROR - Error reconciling Bank Transfer 5918: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5919: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,374 - ERROR - Error reconciling Bank Transfer 5919: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5920: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,438 - ERROR - Error reconciling Bank Transfer 5920: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5921: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,495 - ERROR - Error reconciling Bank Transfer 5921: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5922: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,552 - ERROR - Error reconciling Bank Transfer 5922: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5923: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,613 - ERROR - Error reconciling Bank Transfer 5923: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5924: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,670 - ERROR - Error reconciling Bank Transfer 5924: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5925: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,713 - ERROR - Error reconciling Bank Transfer 5925: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5926: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,788 - ERROR - Error reconciling Bank Transfer 5926: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5927: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,847 - ERROR - Error reconciling Bank Transfer 5927: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5928: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,903 - ERROR - Error reconciling Bank Transfer 5928: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5929: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,932 - ERROR - Error reconciling Bank Transfer 5929: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5930: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,961 - ERROR - Error reconciling Bank Transfer 5930: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5931: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:32,991 - ERROR - Error reconciling Bank Transfer 5931: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5938: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,020 - ERROR - Error reconciling Bank Transfer 5938: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5939: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,050 - ERROR - Error reconciling Bank Transfer 5939: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5940: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,080 - ERROR - Error reconciling Bank Transfer 5940: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5942: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,107 - ERROR - Error reconciling Bank Transfer 5942: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5943: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,137 - ERROR - Error reconciling Bank Transfer 5943: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5945: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,167 - ERROR - Error reconciling Bank Transfer 5945: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5946: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,197 - ERROR - Error reconciling Bank Transfer 5946: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5947: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,225 - ERROR - Error reconciling Bank Transfer 5947: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5948: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,256 - ERROR - Error reconciling Bank Transfer 5948: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5949: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,287 - ERROR - Error reconciling Bank Transfer 5949: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5951: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,317 - ERROR - Error reconciling Bank Transfer 5951: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5952: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,346 - ERROR - Error reconciling Bank Transfer 5952: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5953: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,376 - ERROR - Error reconciling Bank Transfer 5953: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5954: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,407 - ERROR - Error reconciling Bank Transfer 5954: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5955: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,437 - ERROR - Error reconciling Bank Transfer 5955: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5956: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,467 - ERROR - Error reconciling Bank Transfer 5956: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5958: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,499 - ERROR - Error reconciling Bank Transfer 5958: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5959: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,531 - ERROR - Error reconciling Bank Transfer 5959: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5960: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,562 - ERROR - Error reconciling Bank Transfer 5960: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5972: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,624 - ERROR - Error reconciling Bank Transfer 5972: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5973: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,655 - ERROR - Error reconciling Bank Transfer 5973: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5974: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,687 - ERROR - Error reconciling Bank Transfer 5974: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5983: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,723 - ERROR - Error reconciling Bank Transfer 5983: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5985: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,752 - ERROR - Error reconciling Bank Transfer 5985: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5986: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,784 - ERROR - Error reconciling Bank Transfer 5986: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5987: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,815 - ERROR - Error reconciling Bank Transfer 5987: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5990: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,846 - ERROR - Error reconciling Bank Transfer 5990: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5993: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,876 - ERROR - Error reconciling Bank Transfer 5993: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 5995: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,906 - ERROR - Error reconciling Bank Transfer 5995: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6003: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,937 - ERROR - Error reconciling Bank Transfer 6003: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6006: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,969 - ERROR - Error reconciling Bank Transfer 6006: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6017: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:33,999 - ERROR - Error reconciling Bank Transfer 6017: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6031: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,061 - ERROR - Error reconciling Bank Transfer 6031: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6038: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,154 - ERROR - Error reconciling Bank Transfer 6038: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6039: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,185 - ERROR - Error reconciling Bank Transfer 6039: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6046: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,218 - ERROR - Error reconciling Bank Transfer 6046: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6047: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,250 - ERROR - Error reconciling Bank Transfer 6047: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6050: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,282 - ERROR - Error reconciling Bank Transfer 6050: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6056: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,313 - ERROR - Error reconciling Bank Transfer 6056: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6059: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,347 - ERROR - Error reconciling Bank Transfer 6059: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34 - reconciliation.mellat_paid_transfer_reconciliation - ERROR - Error reconciling Bank Transfer 6060: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
2025-08-16 23:20:34,380 - ERROR - Error reconciling Bank Transfer 6060: 'amount'
Traceback (most recent call last):
  File "e:\Work Space\Reconciliation\reconciliation\mellat_reconciliation\mellat_paid_transfer_reconciliation.py", line 77, in _reconcile_single_transfer
    fee = bank_amount - match['amount']
                        ~~~~~^^^^^^^^^^
KeyError: 'amount'
